### ISSUE TITLE
NoSuchMethodError when attempting to surface error

### ISSUE THREAD

**Issue by tmlbl** [ArpNetworking/metrics-apache-http-sink-extra#29]
Given the following example program:
```java
package com.smartsheet.hellomad;

import com.arpnetworking.metrics.impl.ApacheHttpSink;
import com.arpnetworking.metrics.Metrics;
import com.arpnetworking.metrics.MetricsFactory;
import com.arpnetworking.metrics.impl.TsdMetricsFactory;

import java.util.Collections;

/**
 * This app just pushes some random garbage to MAD
 */
public class App
{
    private static MetricsFactory mkMetricsFactory() {
        String madURI = System.getenv("MAD_URI");
        if (madURI == null) {
            System.out.println("ERROR: Must set MAD_URI");
            System.exit(1);
        }
        return new TsdMetricsFactory.Builder()
                .setServiceName("HelloMad")
                .setClusterName("Hello-Cluster")
                .setHostName("hello-mad.example.com")
                .setSinks(Collections.singletonList(
                        new ApacheHttpSink.Builder()
                                .setMaxBatchSize(1000)
                                .setEmptyQueueSleepMillis(1000)
                                .setBufferSize(100000)
                                .setParallelism(1)
                                .setUri(madURI)
                                .build()
                )).build();
    }

    public static void main(String[] args)
    {
        MetricsFactory metricsFactory = mkMetricsFactory();
        Metrics metrics = metricsFactory.create();
        metrics.createCounter("stuff");

        while (true) {
            System.out.println("Incrementing stuff");
            metrics.incrementCounter("stuff");
            try {
                Thread.sleep(1000L);
            } catch (Exception e) {
                break;
            }
        }

        metrics.close();
    }
}
```
If a `MAD_URI` is given which is invalid or unreachable, we get the following output:
```
Exception in thread "main" java.lang.NoSuchMethodError: com.arpnetworking.metrics.impl.WarningSink.<init>(Ljava/util/List;)V
	at com.arpnetworking.metrics.impl.ApacheHttpSink$Builder.build(ApacheHttpSink.java:376)
	at com.smartsheet.hellomad.App.mkMetricsFactory(App.java:32)
	at com.smartsheet.hellomad.App.main(App.java:38)
```
Which appears to be an error internal to the library, not the one caused by the user.

**Comment by vjkoskela** [comment]
@tmlbl Did you mean to close this issue? 

If not, could you include the versions of the client library and apache sink extra that your project is using. Thanks!

**Comment by tmlbl** [comment]
I was using these version from Maven Central:

**Comment by vjkoskela** [comment]
The `com.arpnetworking.metrics:sink-http-apache:0.1.1` was replaced by `com.arpnetworking.metrics.extras:apache-http-sink-extra:*` about two years ago.

See: https://github.com/ArpNetworking/metrics-apache-http-sink-extra/commit/66389f4b3fea1f2fd90d35c4c28642523e728e94

There have been several releases of the `ApacheSink` since that time. Your `pom.xml` file is using the latest `metrics-client` version which is no longer compatible with the deprecated `sink-http-apache`. 

You should replace the dependencies you listed with:

```
    <dependency>
      <groupId>com.arpnetworking.metrics</groupId>
      <artifactId>metrics-client</artifactId>
      <version>0.10.0</version>
    </dependency>
    <dependency>
      <groupId>com.arpnetworking.metrics.extras</groupId>
      <artifactId>apache-http-sink-extra</artifactId>
      <version>0.9.1</version>
    </dependency>
```

And then update your code; specifically:

```
                                .setEmptyQueueSleepMillis(1000)
```

with:

```
                                .setEmptyQueueInterval(Duration.ofMillis(1000))
```

Along with the additional import:

```
import java.time.Duration;
```

Additionally, you need to supply `java.net.URI` instead of a `String:

```
                                .setUri(new URI(madURI))
```

Along with the additional import:

```
import java.net.URI;
```

Finally, add handling of the `URISyntaxException` that can be thrown by the `URI` constructor.

If you set a `URI` without a scheme the client incorrectly throws a `NullPointerException`. However, the `URI` must be set to either `http` or `https` URI; so this should not be a problem when configured correctly. However, I have submitted a patch to ensure the correct error handling behavior occurs if a `URI` without a scheme is provided.

https://github.com/ArpNetworking/metrics-apache-http-sink-extra/pull/30

**Comment by vjkoskela** [comment]
The fix to a `null` schema on the `URI` instance has been released. Resolving. Please feel free to re-open if you have any further questions about this issue.
